Added python as a required build dependency.
westermo/netbox pull request #12
Opened 2021-09-14 08:58 UTC by jorgensigvardsson

Turns out python is needed for (at least) netbox_os_zero_defconfig.

2021-09-14 13:20 UTC, jorgensigvardsson commented
It also turns out that the file `/etc/qemu/bridge.conf` does not exist in all systems (Ubuntu 20.04 does not include it), so the file might need to be created. It is also necessary to build an os image before you can run `make run`. Updated README to include this information.

2021-09-14 14:30 UTC, troglobit requested changes
This is great, just some form to consider.  Git commit messages must be kept to 
    - Brief summary on first line
    - Empty second line
    - Full description in body -- optional if summary is sufficient
    - Signed-off-by at the end

See formatting in previous commits.  Please update both commits to match this.  You can force-push to your branch to update the pull request.

2021-09-17 11:39 UTC, jorgensigvardsson commented
Aaah, so the PR isn't squashed into one commit on your end? I'll squash and amend on my end, and I assume it'll adjust itself "automagically". I might have to reissue the PR in case github causes issues with my history rewrite. :)

2021-09-18 07:52 UTC, troglobit commented
Thanks!

I can squash and merge easily from the web interface, but I cannot update commit messages.  We're picky on stuff like this, as are most upstream projects, so this seemed like the perfect opportunity to "ease you" into it :)

I'll merge as soon as the tests complete.

2021-09-18 07:52 UTC, troglobit approved these changes

2021-09-23 06:29 UTC, merged